project_id = "bvmrvturdajexmwnqjwy"

[auth]
enabled = true
site_url = "https://preview--kapalin-tales-store.lovable.app"
additional_redirect_urls = ["https://kapalin-tales-store.lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false