// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvmrvturdajexmwnqjwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bXJ2dHVyZGFqZXhtd25xand5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDg2MDUsImV4cCI6MjA3MDk4NDYwNX0.MWN4-ASaeSRpGeMUztLuJxbO3SCrB_DvHviKCGQvM9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});