// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://fgmdpbyjfnmjellahgpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbWRwYnlqZm5tamVsbGFoZ3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODExOTIsImV4cCI6MjA3MTg1NzE5Mn0.3bOWgjpbMEzJ1HTXcq5gFIT9K8o6yGmcKEPcdHq93ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});